// Generated by build.py -- do not edit.
window.PICKER_DATA = {
  "competitions": [
    {
      "cards": 10,
      "day": "Monday",
      "division": "B2",
      "draw_source": "cards",
      "errors": 0,
      "generated": "2026-09-21T09:04:36",
      "has_data": true,
      "href": "monday-division-b2/index.html",
      "id": "monday-division-b2",
      "label": "Monday Division B2",
      "ladder_complete": false,
      "leader": null,
      "percent": 50,
      "rejected": 0,
      "rounds_played": 5,
      "rounds_total": 10,
      "season_key": "",
      "season_label": "",
      "teams": 5,
      "warnings": 8
    },
    {
      "cards": 15,
      "day": "Tuesday",
      "division": "C",
      "draw_source": "cards",
      "errors": 0,
      "generated": "2026-09-21T09:04:36",
      "has_data": true,
      "href": "tuesday-division-c/index.html",
      "id": "tuesday-division-c",
      "label": "Tuesday Division C",
      "ladder_complete": true,
      "leader": {
        "name": "UQ Iguanas",
        "value": 6.18
      },
      "percent": 50,
      "rejected": 0,
      "rounds_played": 5,
      "rounds_total": 10,
      "season_key": "",
      "season_label": "",
      "teams": 6,
      "warnings": 8
    }
  ],
  "generated": "2026-09-21T09:04:36",
  "seasons_mode": "single",
  "subtitle": "2 of 2 competitions with results",
  "theme_key": "the-university-of-queensland-tennis-club-inc-theme",
  "title": "THE UNIVERSITY OF QUEENSLAND TENNIS CLUB INC season dashboards"
};
